/**
 * Central registry of audit-log action codes.
 *
 * Audit actions were previously passed as free-form string literals scattered
 * across ~36 service files, which made them impossible to grep reliably and
 * easy to typo. This module is the single source of truth: reference
 * `AUDIT_ACTIONS.CREATE_PATIENT` instead of the raw `'CREATE_PATIENT'`.
 *
 * `logAudit` / `logAuditSafe` still accept a plain `string` (so existing call
 * sites keep working and this can be adopted incrementally), but new code
 * should use these constants.
 */
export const AUDIT_ACTIONS = {
  // Patient / registry
  CREATE_PATIENT: 'CREATE_PATIENT',
  UPDATE_PATIENT: 'UPDATE_PATIENT',
  ARCHIVE_PATIENT: 'ARCHIVE_PATIENT',
  UNARCHIVE_PATIENT: 'UNARCHIVE_PATIENT',

  // Clinical records
  CREATE_MEDICAL_RECORD: 'CREATE_MEDICAL_RECORD',
  UPDATE_MEDICAL_RECORD: 'UPDATE_MEDICAL_RECORD',
  CREATE_ENCOUNTER: 'CREATE_ENCOUNTER',
  TRANSITION_ENCOUNTER: 'TRANSITION_ENCOUNTER',
  CREATE_REFERRAL: 'CREATE_REFERRAL',
  UPDATE_REFERRAL: 'UPDATE_REFERRAL',
  CREATE_FOLLOW_UP: 'CREATE_FOLLOW_UP',
  UPDATE_FOLLOW_UP: 'UPDATE_FOLLOW_UP',
  DELETE_PROBLEM: 'DELETE_PROBLEM',
  PROBLEM_UPDATED: 'PROBLEM_UPDATED',

  // Triage
  TRIAGE_RECORDED: 'TRIAGE_RECORDED',
  TRIAGE_STATUS_CHANGE: 'TRIAGE_STATUS_CHANGE',

  // Lab
  CREATE_LAB_ORDER: 'CREATE_LAB_ORDER',
  UPDATE_LAB_RESULT: 'UPDATE_LAB_RESULT',

  // Pharmacy / medication
  PRESCRIPTION_CREATED: 'PRESCRIPTION_CREATED',
  PRESCRIPTION_UPDATED: 'PRESCRIPTION_UPDATED',
  PRESCRIPTION_DISPENSED: 'PRESCRIPTION_DISPENSED',
  MEDICATION_ADMINISTERED: 'MEDICATION_ADMINISTERED',
  MEDICATION_ADMIN_VOIDED: 'MEDICATION_ADMIN_VOIDED',
  PHARMACY_STOCK_IN: 'PHARMACY_STOCK_IN',
  CONTROLLED_SUBSTANCE_MOVEMENT: 'CONTROLLED_SUBSTANCE_MOVEMENT',

  // Nurse shift handoff
  SHIFT_HANDOFF_SIGNED: 'SHIFT_HANDOFF_SIGNED',
  SHIFT_HANDOFF_ACKNOWLEDGED: 'SHIFT_HANDOFF_ACKNOWLEDGED',
  SHIFT_HANDOFF_UNACKNOWLEDGED: 'SHIFT_HANDOFF_UNACKNOWLEDGED',

  // MCH / CRVS
  REGISTER_BIRTH: 'REGISTER_BIRTH',
  REGISTER_DEATH: 'REGISTER_DEATH',
  ANC_HIGH_RISK_ALERT: 'ANC_HIGH_RISK_ALERT',

  // Blood bank
  ADD_BLOOD_UNIT: 'ADD_BLOOD_UNIT',
  UPDATE_BLOOD_UNIT: 'UPDATE_BLOOD_UNIT',
  RESERVE_BLOOD_UNIT: 'RESERVE_BLOOD_UNIT',
  CROSSMATCH_BLOOD_UNIT: 'CROSSMATCH_BLOOD_UNIT',
  TRANSFUSE_BLOOD_UNIT: 'TRANSFUSE_BLOOD_UNIT',
  DISCARD_BLOOD_UNIT: 'DISCARD_BLOOD_UNIT',

  // Emergency preparedness
  ACTIVATE_EMERGENCY: 'ACTIVATE_EMERGENCY',
  DEACTIVATE_EMERGENCY: 'DEACTIVATE_EMERGENCY',
  CREATE_EMERGENCY_PLAN: 'CREATE_EMERGENCY_PLAN',
  UPDATE_EMERGENCY_PLAN: 'UPDATE_EMERGENCY_PLAN',
  DELETE_EMERGENCY_PLAN: 'DELETE_EMERGENCY_PLAN',

  // Appointments / availability / scheduling
  CREATE_APPOINTMENT: 'CREATE_APPOINTMENT',
  UPDATE_APPOINTMENT: 'UPDATE_APPOINTMENT',
  RESCHEDULE_APPOINTMENT: 'RESCHEDULE_APPOINTMENT',
  CREATE_AVAILABILITY: 'CREATE_AVAILABILITY',
  CANCEL_AVAILABILITY: 'CANCEL_AVAILABILITY',
  CREATE_SCHEDULE: 'CREATE_SCHEDULE',
  UPDATE_SCHEDULE: 'UPDATE_SCHEDULE',
  DELETE_SCHEDULE: 'DELETE_SCHEDULE',
  GENERATE_REMINDERS: 'GENERATE_REMINDERS',

  // Communication
  CREATE_ANNOUNCEMENT: 'CREATE_ANNOUNCEMENT',
  DELETE_MESSAGE: 'DELETE_MESSAGE',
  EDIT_MESSAGE: 'EDIT_MESSAGE',
  DELETE_CONVERSATION: 'DELETE_CONVERSATION',

  // Telehealth
  CREATE_TELEHEALTH: 'CREATE_TELEHEALTH',
  UPDATE_TELEHEALTH: 'UPDATE_TELEHEALTH',

  // Assets / facility ops
  ASSET_REGISTERED: 'ASSET_REGISTERED',
  ASSET_STATUS_CHANGED: 'ASSET_STATUS_CHANGED',
  ASSET_MAINTENANCE: 'ASSET_MAINTENANCE',

  // HR
  LEAVE_REQUESTED: 'LEAVE_REQUESTED',
  LEAVE_CANCELLED: 'LEAVE_CANCELLED',
  PAYROLL_ENTRY_CREATED: 'PAYROLL_ENTRY_CREATED',
  PAYROLL_STATUS: 'PAYROLL_STATUS',

  // Billing / payments / claims
  CLAIM_SUBMITTED: 'CLAIM_SUBMITTED',
  FEE_CREATED: 'FEE_CREATED',
  FEE_UPDATED: 'FEE_UPDATED',
  FEE_DELETED: 'FEE_DELETED',
  PAYMENT_REVERSED: 'PAYMENT_REVERSED',
  PAYMENT_STATUS_UPDATED: 'PAYMENT_STATUS_UPDATED',
  PAYMENT_PLAN_CREATED: 'PAYMENT_PLAN_CREATED',
  ADJUSTMENT_CREATED: 'ADJUSTMENT_CREATED',
  REFUND_ISSUED: 'REFUND_ISSUED',
  DELETE_PAYMENT_METHOD: 'DELETE_PAYMENT_METHOD',

  // Facility assessments
  CREATE_FACILITY_ASSESSMENT: 'CREATE_FACILITY_ASSESSMENT',
} as const;

/** A known audit-action code. (Plain strings are still accepted by logAudit
 *  for backward compatibility; this union documents the canonical set.) */
export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
