/**
 * DHIS2 dataElement UID mapping (KAN-57 / MED-07).
 *
 * `generateDHIS2Export()` emits readable concept names — 'TOTAL_HOSPITALS',
 * 'IMM_BCG_COMPLETED'. DHIS2 does not accept those: every `dataElement` must be
 * an 11-character alphanumeric UID minted by the receiving DHIS2 instance. Post
 * a payload of concept names to the South Sudan HMIS and it rejects the rows,
 * quietly, as validation errors.
 *
 * The UIDs cannot live in this repo. They are generated by whichever DHIS2
 * instance the deployment reports to, so they differ between the national HMIS,
 * a training server, and any partner instance. Hard-coding one set would be
 * wrong everywhere else, and inventing plausible-looking ones would be worse
 * than emitting concept names — a well-formed but incorrect UID posts silently
 * against the WRONG data element.
 *
 * So the map is supplied per deployment, and unmapped concepts pass through
 * unchanged. Nothing about the current behaviour changes until an operator
 * configures a map; what changes is that the export now TELLS you the payload
 * will be rejected instead of failing silently at the far end.
 *
 * ## Configuring
 *
 * Set `DHIS2_ELEMENT_MAP` (server) or `NEXT_PUBLIC_DHIS2_ELEMENT_MAP` (browser
 * export UI) to a JSON object of concept → UID:
 *
 *     DHIS2_ELEMENT_MAP='{"TOTAL_HOSPITALS":"Uvn6LCg7dVU","OPD_ATTENDANCE_TOTAL":"s46m5MS0hxu"}'
 *
 * Pull the real values from the target instance:
 *
 *     curl -u user:pass 'https://<dhis2-host>/api/dataElements?fields=id,name,code&paging=false'
 *
 * Match on `code` where your HMIS defines one — codes are stable across
 * instances, UIDs are not.
 */

/** DHIS2 UIDs are exactly 11 alphanumeric characters and must start with a letter. */
const DHIS2_UID_PATTERN = /^[A-Za-z][A-Za-z0-9]{10}$/;

/** True if `value` is a syntactically valid DHIS2 UID. */
export function isDhis2Uid(value: string): boolean {
  return DHIS2_UID_PATTERN.test(value);
}

/**
 * Every concept `generateDHIS2Export()` can emit. Kept as a literal list so an
 * operator can diff their configured map against it and see what is still
 * unmapped, and so `validateDataElements()` can name the gaps precisely.
 */
export const DHIS2_CONCEPTS = [
  // Facility & workforce
  'TOTAL_HOSPITALS', 'TOTAL_PATIENTS', 'TOTAL_BEDS', 'TOTAL_DOCTORS',
  'TOTAL_NURSES', 'TOTAL_CLINICAL_OFFICERS', 'HIS_WORKFORCE',
  'FACILITIES_ASSESSED',
  // OPD attendance
  'OPD_ATTENDANCE_TOTAL', 'OPD_ATTENDANCE_NEW', 'OPD_ATTENDANCE_REPEAT',
  'OPD_ATTENDANCE_BY_CATEGORY',
  // Births & deaths
  'BIRTHS_REGISTERED', 'BIRTHS_MALE', 'BIRTHS_FEMALE', 'BIRTHS_CAESAREAN',
  'FACILITY_BIRTHS', 'FACILITY_DEATHS',
  'DEATHS_REGISTERED', 'DEATHS_WITH_ICD11', 'MATERNAL_DEATHS',
  'UNDER5_DEATHS', 'NEONATAL_DEATHS',
  'DEATH_NOTIFICATION_RATE', 'DEATH_REGISTRATION_RATE',
  // ANC & immunisation
  'ANC_MOTHERS_TOTAL', 'ANC_VISITS_TOTAL', 'ANC_4PLUS_VISITS', 'ANC_HIGH_RISK',
  'IMM_CHILDREN_TOTAL', 'IMM_BCG_COMPLETED', 'IMM_PENTA3_COMPLETED',
  'IMM_MEASLES1_COMPLETED', 'IMM_DEFAULTERS',
  // Surveillance & referral
  'ACTIVE_DISEASE_ALERTS', 'TOTAL_REFERRALS',
  // Laboratory
  'LAB_TESTS_TOTAL', 'LAB_TESTS_COMPLETED', 'LAB_TESTS_PENDING',
  'LAB_TESTS_IN_PROGRESS', 'LAB_CRITICAL_RESULTS',
  // Pharmacy
  'PRESCRIPTIONS_TOTAL', 'PRESCRIPTIONS_DISPENSED', 'PRESCRIPTIONS_PENDING',
  // HIS performance
  'DATA_QUALITY_SCORE', 'DHIS2_ADOPTION_RATE',
  'REPORTING_COMPLETENESS', 'REPORTING_TIMELINESS',
] as const;

export type DHIS2Concept = (typeof DHIS2_CONCEPTS)[number];

export interface DHIS2ElementMapResult {
  /** concept → UID, only for entries that parsed and looked like UIDs. */
  map: Record<string, string>;
  /** Problems with the configured map itself (bad JSON, malformed UIDs). */
  configErrors: string[];
}

let cached: DHIS2ElementMapResult | null = null;

/**
 * Parse the configured element map. Invalid entries are dropped rather than
 * thrown on — a typo in one UID must not take down the whole export, and the
 * rejected entry is reported so it is visible rather than silently ignored.
 */
export function loadElementMap(
  env: Record<string, string | undefined> = process.env,
): DHIS2ElementMapResult {
  const raw = env.DHIS2_ELEMENT_MAP || env.NEXT_PUBLIC_DHIS2_ELEMENT_MAP || '';
  if (!raw.trim()) return { map: {}, configErrors: [] };

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return {
      map: {},
      configErrors: ['DHIS2_ELEMENT_MAP is not valid JSON — expected {"CONCEPT":"dhis2Uid11"}.'],
    };
  }
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    return { map: {}, configErrors: ['DHIS2_ELEMENT_MAP must be a JSON object of concept → UID.'] };
  }

  const map: Record<string, string> = {};
  const configErrors: string[] = [];
  for (const [concept, uid] of Object.entries(parsed as Record<string, unknown>)) {
    if (typeof uid !== 'string') {
      configErrors.push(`DHIS2_ELEMENT_MAP["${concept}"] is not a string.`);
      continue;
    }
    if (!isDhis2Uid(uid)) {
      configErrors.push(
        `DHIS2_ELEMENT_MAP["${concept}"] = "${uid}" is not a valid DHIS2 UID ` +
          '(11 alphanumeric characters, starting with a letter).',
      );
      continue;
    }
    if (!(DHIS2_CONCEPTS as readonly string[]).includes(concept)) {
      configErrors.push(
        `DHIS2_ELEMENT_MAP["${concept}"] does not match any concept this export emits — ` +
          'check for a typo; it will never be used.',
      );
      continue;
    }
    map[concept] = uid;
  }
  return { map, configErrors };
}

/** Test seam — clears the module-level cache. */
export function _resetElementMapCache(): void {
  cached = null;
}

function elementMap(): DHIS2ElementMapResult {
  if (!cached) cached = loadElementMap();
  return cached;
}

/**
 * Translate a concept name to its configured DHIS2 UID. Falls back to the
 * concept name unchanged when unmapped, so an unconfigured deployment behaves
 * exactly as it did before — just with the warning surfaced by
 * `validateDataElements()`.
 */
export function resolveDataElement(concept: string): string {
  return elementMap().map[concept] ?? concept;
}

export interface DHIS2ElementValidation {
  /** True when every emitted dataElement is a syntactically valid DHIS2 UID. */
  valid: boolean;
  /** Concepts with no configured UID — DHIS2 will reject these rows. */
  unmappedConcepts: string[];
  /** Problems with DHIS2_ELEMENT_MAP itself. */
  configErrors: string[];
  /** One-line human-readable summary, or '' when everything is mapped. */
  warning: string;
}

/**
 * Check a set of emitted dataElement values against the DHIS2 UID rule.
 * Reports rather than throws: a facility must still be able to produce and
 * inspect an export locally even when the UID map has not been configured yet.
 */
export function validateDataElements(dataElements: string[]): DHIS2ElementValidation {
  const { configErrors } = elementMap();
  const unmappedConcepts = [...new Set(dataElements.filter((d) => !isDhis2Uid(d)))].sort();

  const parts: string[] = [];
  if (unmappedConcepts.length > 0) {
    parts.push(
      `${unmappedConcepts.length} dataElement(s) are concept names, not DHIS2 UIDs ` +
        `(${unmappedConcepts.slice(0, 3).join(', ')}${unmappedConcepts.length > 3 ? ', …' : ''}). ` +
        'DHIS2 will reject these rows. Configure DHIS2_ELEMENT_MAP — see lib/services/dhis2-element-map.ts.',
    );
  }
  parts.push(...configErrors);

  return {
    valid: unmappedConcepts.length === 0 && configErrors.length === 0,
    unmappedConcepts,
    configErrors,
    warning: parts.join(' '),
  };
}
