import type { TourStep } from './types';

// Walks a Clinical Officer through a full visit end to end: the dashboard
// they land on after login, finding a patient, then every stage of the
// consultation wizard in order (History -> Intake -> Examination ->
// Assessment -> Orders -> Plan & checkout). Section anchors correspond to
// `data-tour="consult-section-N"` on each SectionHeader in
// `consultation/page.tsx`, and stage anchors to `data-tour-stage="N"` on the
// wizard's step-indicator buttons.
export const clinicalOfficerTourSteps: TourStep[] = [
  {
    id: 'welcome',
    route: '/dashboard',
    target: '.ehr-care-greeting',
    title: 'Welcome to TamamHealth',
    body: "Let's walk through a Clinical Officer's day — from your schedule to finishing a consultation. Use Back and Next anytime, or skip to explore on your own.",
    placement: 'bottom',
  },
  {
    id: 'dash-view-toggle',
    route: '/dashboard',
    target: '.ehr-clinical-dashboard-tabs .ehr-segmented',
    title: 'Dashboard & Calendar',
    body: 'Dashboard shows the day as a worklist. Calendar shows the same appointments laid out across the month.',
    placement: 'bottom',
  },
  {
    id: 'dash-calendar',
    route: '/dashboard',
    target: '.ehr-left-rail .ehr-mini-calendar',
    title: 'Jump to any day',
    body: 'Pick a date to see who is booked, or use "Go to today" to snap back to now.',
    placement: 'right',
  },
  {
    id: 'dash-schedule',
    route: '/dashboard',
    target: '.ehr-appointment-list',
    title: 'Your schedule',
    body: 'Everyone booked with you, split into Scheduled, In Office, and Finished. Click a row to open that patient’s chart.',
    placement: 'top',
  },
  {
    id: 'dash-outstanding',
    route: '/dashboard',
    target: '.ehr-outstanding-card',
    title: 'Outstanding items',
    body: 'Referrals, lab results, and other follow-ups waiting on you — grouped here so nothing slips through.',
    placement: 'left',
  },
  {
    id: 'dash-intake',
    route: '/dashboard',
    target: '.ehr-schedule-actions button.primary',
    title: 'Send a patient to intake',
    body: 'Route a walk-in to Patient Intake to capture vitals and history before you see them.',
    placement: 'bottom',
  },
  {
    id: 'top-search',
    route: '/dashboard',
    target: '.ehr-top-search',
    title: 'Find any patient',
    body: 'Search by name, hospital number, or phone from anywhere in the app.',
    placement: 'bottom',
  },
  {
    id: 'top-modules',
    route: '/dashboard',
    target: '.ehr-top-modules',
    title: 'Switch modules',
    body: 'Jump between Patients, Consultation, Wards, Lab, Pharmacy, Referrals, and everything else you have access to.',
    placement: 'bottom',
  },
  {
    id: 'consult-stepper',
    route: '/consultation',
    target: '.ehr-soap-stepper',
    title: 'The consultation wizard',
    body: 'A visit moves through these stages in order. Click any stage to jump there, or use Back/Next as you go.',
    placement: 'bottom',
  },
  {
    id: 'consult-history',
    route: '/consultation',
    target: '[data-tour="consult-section-0"]',
    title: 'Start with history',
    body: 'Capture the chief complaint, history of present illness, past medical history, and social/family history.',
    placement: 'bottom',
    preClickSelector: '[data-tour-stage="0"]',
  },
  {
    id: 'consult-exam',
    route: '/consultation',
    target: '[data-tour="consult-section-2"]',
    title: 'Physical exam',
    body: 'Record exam findings by system as you go through the visit.',
    placement: 'bottom',
    preClickSelector: '[data-tour-stage="2"]',
  },
  {
    id: 'consult-diagnosis',
    route: '/consultation',
    target: '[data-tour="consult-section-4"]',
    title: 'Assessment & diagnosis',
    body: 'Add ICD-11 diagnoses — favorites and recently used codes are one click away.',
    placement: 'bottom',
    preClickSelector: '[data-tour-stage="3"]',
  },
  {
    id: 'consult-prescriptions',
    route: '/consultation',
    target: '[data-tour="consult-section-5"]',
    title: 'Prescriptions',
    body: 'Prescribe medications here — Pharmacy sees the order the moment you save.',
    placement: 'bottom',
    preClickSelector: '[data-tour-stage="4"]',
  },
  {
    id: 'consult-labs',
    route: '/consultation',
    target: '[data-tour="consult-section-6"]',
    title: 'Order labs',
    body: 'Send tests straight to the lab queue. Results flow back into this same chart once they’re ready.',
    placement: 'bottom',
    preClickSelector: '[data-tour-stage="4"]',
  },
  {
    id: 'consult-referral',
    route: '/consultation',
    target: '[data-tour="consult-section-10"]',
    title: 'Refer when needed',
    body: 'Refer to a specialist or a higher-level facility right from the visit — no separate form to fill out.',
    placement: 'top',
    preClickSelector: '[data-tour-stage="5"]',
  },
  {
    id: 'finish',
    route: '/consultation',
    target: '.ehr-soap-stepper',
    title: 'You’re ready',
    body: 'That’s the full Clinical Officer workflow, start to finish. You can replay this tour anytime from your profile menu.',
    placement: 'bottom',
    preClickSelector: '[data-tour-stage="6"]',
  },
];
